# -*- coding: utf-8 -*-
"""Predicting_100_centruries_record.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-astSPwlz63pBgw2lIP38xdj_OkjckKt

Importing the libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score

"""Importing the dataset

"""

#laoding the dataset
dataset = pd.read_csv('/content/virat_kohli_odi_century_progression.csv')

print(dataset.head)

import pandas as pd

# Create new rows for 2024 and 2025 with placeholder values
new_data = pd.DataFrame({
    'year': [2024, 2025],
    'matches': [295, 308],
    'centuries': [51, 54],

})

# Concatenate the new data with the existing dataset
dataset = pd.concat([dataset, new_data], ignore_index=True)

print("Dataset after adding rows for 2024 and 2025:")
display(dataset.tail())

dataset.rename(columns={'centuries':'ODI Centuries'}, inplace=True)

dataset.head()

dataset.info()

dataset.shape

"""// BF' stands for 'Balls Faced', which represents the number of deliveries a batsman has received."""

dataset.describe()

dataset.info()

dataset['Total Centuries'] = (dataset['ODI Centuries'] + 31).astype(int)
print("The 'Century' column has been created with numerical values (1 for century, 0 otherwise).")

dataset.corr()

X = dataset[['Total Centuries']]
Y = dataset[['year', 'matches', 'ODI Centuries']]

print("Head of new X DataFrame:")
print(X.head())
print("\nHead of new Y DataFrame:")
print(Y.head())

print(X)
print(Y)

"""Train and Test split"""

X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.1, random_state=1)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of Y_train: {Y_train.shape}")
print(f"Shape of Y_test: {Y_test.shape}")

"""Model traing--> linearRegression"""

model = LinearRegression()
model.fit(X_train,Y_train)
print("Linear Regression model has been trained with updated X and Y variables.")

Y_pred = model.predict(X_test)
print("Predictions have been made on the test set.")

X_train

Y_train

"""Accuracy"""

X_train_prediction = model.predict(X_train)
print("Predictions have been made on the training set.")
# For regression, accuracy_score is typically not used directly.
# Let's use r2_score for regression model evaluation.
X_train_r2 = r2_score(Y_train, X_train_prediction)
print(f"R2 Score on training set: {X_train_r2}")

Y_test_r2 = r2_score(Y_test, Y_pred)
print(f"R2 Score on test set: {Y_test_r2}")

"""Making the predicting system"""

input_total_centuries = 100
input_data = pd.DataFrame({'Total Centuries': [input_total_centuries]})
prediction = model.predict(input_data)
precition_df = pd.DataFrame(prediction, columns=['Year', 'Matches', 'ODI Centuries'])
print("Predicted Values:")
print(precition_df)

